/* Verify read-only MPQE stream-provider opening with public fixtures. */
#include "test-mpq-helper.h"

#include "mpq-internal.h"
#include "mpq-mpqe.h"
#include "mpq-stream.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const uint8_t auth_code[] = "LIBMPQ-MPQE-TEST-AUTH-CODE-00001";

/* Verify MPQE key derivation using a synthetic known-answer vector. */
static int
test_key_derivation(void)
{
    static const uint8_t expected_key[] = "expand 32-byte k"
                                          "TEST00000001PQE-0000DE-0PQ-M0000H-COLIBM0000-AUT";
    uint8_t key[LIBMPQ_MPQE_CHUNK_SIZE];
    int32_t result;

    TEST_CHECK(sizeof(expected_key) - 1U == sizeof(key));
    result = libmpq__mpqe_key(key, auth_code, sizeof(auth_code) - 1U);
    if (result == 0)
        result = memcmp(key, expected_key, sizeof(key));
    libmpq__mpqe_clear(key, sizeof(key));
    TEST_CHECK(result == 0);
    return 0;
}

/* Verify a vector generated by a standalone StormLib-compatible reference. */
static int
test_chunk_transform(void)
{
    static const uint8_t plaintext[] = {
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19,
        0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26,
        0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33,
        0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f,
    };
    static const uint8_t ciphertext[] = {
        0x7e, 0xb1, 0xb3, 0x4a, 0x17, 0xaf, 0xdf, 0x72, 0x5c, 0xb8, 0x37, 0x37, 0x1e,
        0x37, 0x2b, 0xd2, 0x25, 0x92, 0xcc, 0x66, 0x76, 0x51, 0xaa, 0xf6, 0x2c, 0x3f,
        0x0f, 0xf7, 0x09, 0x31, 0xcb, 0xd6, 0x7f, 0x16, 0xbd, 0xcd, 0x2f, 0xe0, 0xb4,
        0xac, 0xab, 0x90, 0xfc, 0xfc, 0x7a, 0x28, 0x7b, 0x7b, 0x63, 0xcf, 0x5d, 0xed,
        0xb5, 0xff, 0x5c, 0x7e, 0x5b, 0xf1, 0x09, 0x75, 0x7f, 0xe2, 0x4e, 0x23,
    };
    uint8_t chunk[LIBMPQ_MPQE_CHUNK_SIZE];
    uint8_t key[LIBMPQ_MPQE_CHUNK_SIZE];
    int32_t result;

    TEST_CHECK(sizeof(plaintext) == sizeof(chunk));
    TEST_CHECK(sizeof(ciphertext) == sizeof(chunk));
    memcpy(chunk, plaintext, sizeof(chunk));
    result = libmpq__mpqe_key(key, auth_code, sizeof(auth_code) - 1U);
    if (result == 0)
        libmpq__mpqe_transform_chunk(chunk, key, UINT64_C(0x123456780));
    if (result == 0)
        result = memcmp(chunk, ciphertext, sizeof(chunk));
    libmpq__mpqe_clear(key, sizeof(key));
    libmpq__mpqe_clear(chunk, sizeof(chunk));
    TEST_CHECK(result == 0);
    return 0;
}

/* Apply the private symmetric transform with a test-owned derived MPQE key. */
static int32_t
transform_chunk(uint8_t chunk[LIBMPQ_MPQE_CHUNK_SIZE], uint64_t offset)
{
    uint8_t key[LIBMPQ_MPQE_CHUNK_SIZE];
    int32_t result;

    result = libmpq__mpqe_key(key, auth_code, sizeof(auth_code) - 1U);
    if (result == 0)
        libmpq__mpqe_transform_chunk(chunk, key, offset);
    libmpq__mpqe_clear(key, sizeof(key));
    return result;
}

/* The raw and MPQE fixtures are paired archive streams with matching bytes. */
typedef struct
{
    const char *raw_name;
    const char *mpqe_name;
    const char *overview_hash;
    uint32_t version;
} mpqe_fixture_s;

static const mpqe_fixture_s fixtures[] = {
    {
        "mpq-v1-features.mpq",
        "mpq-v1-features.mpqe",
        "722f1acc2acd306abaed0466ffbbfd568e09f5e7da8d63eba86f19c1c2adde73",
        1,
    },
    {
        "mpq-v2-features.mpq",
        "mpq-v2-features.mpqe",
        "722f1acc2acd306abaed0466ffbbfd568e09f5e7da8d63eba86f19c1c2adde73",
        2,
    },
};

/* Extract every advertised fixture member through both raw and MPQE streams. */
static int
test_fixture_members(mpq_archive_s *archive, const char *raw_path, uint32_t version)
{
    static const char *const names[] = {
        "overview.txt",     "implode.txt",     "huffman.txt", "zlib.txt",
        "pkware.txt",       "bzip2.txt",       "chain.txt",   "encrypted-compress.txt",
        "wave-mono.wav",    "wave-stereo.wav", "sparse.txt",  "sparse-zlib.txt",
        "sparse-bzip2.txt", "lzma.txt",        "(listfile)",  "(attributes)",
    };
    mpq_archive_s *raw_archive = NULL;
    uint8_t *raw_data = NULL;
    uint8_t *mpqe_data = NULL;
    size_t raw_size;
    size_t mpqe_size;
    size_t i;

    TEST_CHECK(libmpq__archive_open(&raw_archive, raw_path, 0) == 0);
    for (i = 0; i < sizeof(names) / sizeof(names[0]); ++i) {
        uint32_t raw_number;
        uint32_t mpqe_number;
        uint32_t verification = UINT32_MAX;
        uint32_t blocks;
        uint32_t block;

        if (version == 1 && strcmp(names[i], "lzma.txt") == 0)
            continue;
        TEST_CHECK(libmpq__file_number(raw_archive, names[i], &raw_number) == 0);
        TEST_CHECK(libmpq__file_number(archive, names[i], &mpqe_number) == 0);
        TEST_CHECK(libmpq__file_blocks(archive, mpqe_number, &blocks) == 0);
        for (block = 0; block < blocks; ++block) {
            uint32_t raw_method = UINT32_MAX;
            uint32_t mpqe_method = UINT32_MAX;
            TEST_CHECK(libmpq__block_compression(raw_archive, raw_number, block, &raw_method) == 0);
            TEST_CHECK(libmpq__block_compression(archive, mpqe_number, block, &mpqe_method) == 0);
            TEST_CHECK(raw_method == mpqe_method);
        }
        TEST_CHECK(
            raw_archive->mpq_block[raw_archive->mpq_map[raw_number].block_table_indices].flags ==
            archive->mpq_block[archive->mpq_map[mpqe_number].block_table_indices].flags
        );
        TEST_CHECK(
            libmpq__file_verify(archive, mpqe_number, LIBMPQ_VERIFY_SECTOR_CRC, &verification) == 0
        );
        TEST_CHECK(verification == 0);
        if (strstr(names[i], ".wav") == NULL && strcmp(names[i], "(attributes)") != 0) {
            verification = UINT32_MAX;
            TEST_CHECK(
                libmpq__file_verify(archive, mpqe_number, LIBMPQ_VERIFY_ALL, &verification) == 0
            );
            TEST_CHECK(verification == 0);
        }
        TEST_CHECK(test_archive_read(raw_archive, raw_number, &raw_data, &raw_size) == 0);
        TEST_CHECK(test_archive_read(archive, mpqe_number, &mpqe_data, &mpqe_size) == 0);
        TEST_CHECK(raw_size == mpqe_size && memcmp(raw_data, mpqe_data, raw_size) == 0);
        free(raw_data);
        free(mpqe_data);
        raw_data = NULL;
        mpqe_data = NULL;
    }
    TEST_CHECK(libmpq__archive_close(raw_archive) == 0);
    return 0;
}

/* Compare random-access MPQE reads with the corresponding raw MPQ fixture. */
static int
test_stream_reads(const char *raw_path, const char *mpqe_path)
{
    mpq_stream_s *stream = NULL;
    uint8_t *raw_data = NULL;
    uint8_t cross_chunk[96];
    uint8_t trailing[64];
    size_t raw_size;
    size_t trailing_size;

    TEST_CHECK(test_read_path(raw_path, &raw_data, &raw_size) == 0);
    TEST_CHECK(raw_size > sizeof(cross_chunk) && raw_size % 64U != 0U);
    TEST_CHECK(
        libmpq__stream_open_mpqe(&stream, mpqe_path, auth_code, sizeof(auth_code) - 1U) == 0
    );
    TEST_CHECK(libmpq__stream_size(stream) == raw_size);
    TEST_CHECK(libmpq__stream_read_at(stream, 32, cross_chunk, sizeof(cross_chunk)) == 0);
    TEST_CHECK(memcmp(cross_chunk, raw_data + 32, sizeof(cross_chunk)) == 0);
    trailing_size = raw_size % 64U;
    TEST_CHECK(
        libmpq__stream_read_at(stream, raw_size - trailing_size, trailing, trailing_size) == 0
    );
    TEST_CHECK(memcmp(trailing, raw_data + raw_size - trailing_size, trailing_size) == 0);
    TEST_CHECK(libmpq__stream_close(stream) == 0);
    free(raw_data);
    return 0;
}

/* Build a temporary MPQE stream to cover an unaligned read through two batches. */
static int
test_stream_cross_batch(void)
{
    enum
    {
        plain_size = 12288 + 31,
        read_offset = 4096 - 19,
        read_size = 4200
    };
    char path[512];
    FILE *file;
    mpq_stream_s *stream = NULL;
    uint8_t plain[plain_size];
    uint8_t encrypted[plain_size];
    uint8_t read_data[read_size];
    size_t chunk;

    test_payload(plain, sizeof(plain), 0x4d505145U);
    memcpy(encrypted, plain, sizeof(encrypted));
    for (chunk = 0; chunk < sizeof(encrypted); chunk += 64U) {
        uint8_t block[64] = { 0 };
        size_t bytes = sizeof(encrypted) - chunk;

        if (bytes > sizeof(block))
            bytes = sizeof(block);
        memcpy(block, encrypted + chunk, bytes);
        TEST_CHECK(transform_chunk(block, chunk) == 0);
        memcpy(encrypted + chunk, block, bytes);
    }
    TEST_CHECK(test_temp_path(path, sizeof(path), "mpqe-batch") == 0);
    file = fopen(path, "wb");
    TEST_CHECK(file != NULL);
    TEST_CHECK(fwrite(encrypted, 1, sizeof(encrypted), file) == sizeof(encrypted));
    TEST_CHECK(fclose(file) == 0);
    TEST_CHECK(libmpq__stream_open_mpqe(&stream, path, auth_code, sizeof(auth_code) - 1U) == 0);
    TEST_CHECK(libmpq__stream_read_at(stream, read_offset, read_data, sizeof(read_data)) == 0);
    TEST_CHECK(memcmp(read_data, plain + read_offset, sizeof(read_data)) == 0);
    TEST_CHECK(libmpq__stream_close(stream) == 0);
    TEST_CHECK(remove(path) == 0);
    return 0;
}

/* Validate parsing, extraction, and cloning for a paired public fixture. */
static int
test_fixture(const mpqe_fixture_s *fixture, size_t index)
{
    char raw_path[512];
    char mpqe_path[512];
    mpq_archive_s *archive = NULL;
    mpq_archive_s *clone = NULL;
    uint8_t wrong_code[sizeof(auth_code) - 1U];
    uint8_t *data = NULL;
    size_t size;
    char hash[65];
    uint32_t version;
    uint32_t files;
    uint32_t number;
    int32_t result;

    TEST_CHECK(snprintf(raw_path, sizeof(raw_path), "%s/%s", FIXTURE_DIR, fixture->raw_name) > 0);
    TEST_CHECK(
        snprintf(mpqe_path, sizeof(mpqe_path), "%s/%s", FIXTURE_DIR, fixture->mpqe_name) > 0
    );
    TEST_CHECK(libmpq__archive_open(&archive, mpqe_path, 0) == LIBMPQ_ERROR_FORMAT);
    TEST_CHECK(archive == NULL);
    if (index == 0) {
        TEST_CHECK(
            libmpq__archive_open_mpqe(&archive, mpqe_path, 0, NULL, 0) == LIBMPQ_ERROR_DECRYPT
        );
        TEST_CHECK(archive == NULL);
        TEST_CHECK(
            libmpq__archive_open_mpqe(&archive, mpqe_path, 0, auth_code, sizeof(auth_code) - 2U) ==
            LIBMPQ_ERROR_DECRYPT
        );
        TEST_CHECK(archive == NULL);
        memcpy(wrong_code, auth_code, sizeof(wrong_code));
        wrong_code[0] ^= 1U;
        result = libmpq__archive_open_mpqe(&archive, mpqe_path, 0, wrong_code, sizeof(wrong_code));
        TEST_CHECK(result < 0);
        TEST_CHECK(archive == NULL);
    }
    TEST_CHECK(
        libmpq__archive_open_mpqe(
            &archive, mpqe_path, index == 0 ? 0 : -1, auth_code, sizeof(auth_code) - 1U
        ) == 0
    );
    TEST_CHECK(libmpq__archive_version(archive, &version) == 0 && version == fixture->version);
    TEST_CHECK(
        libmpq__archive_files(archive, &files) == 0 && files == (fixture->version == 2 ? 16 : 15)
    );
    TEST_CHECK(libmpq__file_number(archive, "overview.txt", &number) == 0);
    TEST_CHECK(test_archive_read(archive, number, &data, &size) == 0);
    TEST_CHECK(test_sha256(data, size, hash) == 0);
    TEST_CHECK(strcmp(hash, fixture->overview_hash) == 0);
    free(data);
    data = NULL;
    TEST_CHECK(test_fixture_members(archive, raw_path, fixture->version) == 0);
    TEST_CHECK(libmpq__archive_clone(&clone, archive) == 0);
    TEST_CHECK(libmpq__archive_close(archive) == 0);
    archive = NULL;
    TEST_CHECK(libmpq__file_number(clone, "overview.txt", &number) == 0);
    TEST_CHECK(test_archive_read(clone, number, &data, &size) == 0);
    TEST_CHECK(test_sha256(data, size, hash) == 0);
    TEST_CHECK(strcmp(hash, fixture->overview_hash) == 0);
    free(data);
    TEST_CHECK(libmpq__archive_close(clone) == 0);
    return test_stream_reads(raw_path, mpqe_path);
}

/* Open failures must clear caller output pointers before stream allocation. */
static int
test_open_failure_output(void)
{
    char missing_path[512];
    mpq_archive_s *archive = (mpq_archive_s *)(uintptr_t)1;

    TEST_CHECK(
        snprintf(missing_path, sizeof(missing_path), "%s/%s", FIXTURE_DIR, "missing.mpq") > 0
    );
    TEST_CHECK(libmpq__archive_open(&archive, missing_path, 0) == LIBMPQ_ERROR_EXIST);
    TEST_CHECK(archive == NULL);

    archive = (mpq_archive_s *)(uintptr_t)1;
    TEST_CHECK(
        libmpq__archive_open_mpqe(&archive, missing_path, 0, auth_code, sizeof(auth_code) - 2U) ==
        LIBMPQ_ERROR_DECRYPT
    );
    TEST_CHECK(archive == NULL);

    archive = (mpq_archive_s *)(uintptr_t)1;
    TEST_CHECK(
        libmpq__archive_open_mpqe(&archive, missing_path, 0, auth_code, sizeof(auth_code) - 1U) ==
        LIBMPQ_ERROR_EXIST
    );
    TEST_CHECK(archive == NULL);
    TEST_CHECK(libmpq__archive_open(NULL, missing_path, 0) == LIBMPQ_ERROR_EXIST);
    TEST_CHECK(
        libmpq__archive_open_mpqe(NULL, missing_path, 0, auth_code, sizeof(auth_code) - 1U) ==
        LIBMPQ_ERROR_EXIST
    );
    return 0;
}

/* Exercise full v1 and v2 fixtures through the public MPQE open path. */
int
main(void)
{
    size_t i;

    TEST_CHECK(test_key_derivation() == 0);
    TEST_CHECK(test_chunk_transform() == 0);
    for (i = 0; i < sizeof(fixtures) / sizeof(fixtures[0]); ++i)
        TEST_CHECK(test_fixture(&fixtures[i], i) == 0);
    TEST_CHECK(test_open_failure_output() == 0);
    TEST_CHECK(test_stream_cross_batch() == 0);
    return 0;
}
