.\" Copyright (c) 2003-2026 Maik Broemme <mbroemme@libmpq.org>
.\"
.\" This manual is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License as
.\" published by the Free Software Foundation; either version 2.1 of
.\" the License, or (at your option) any later version.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this manual; if not, see <https://www.gnu.org/licenses/>.
.TH LIBMPQ__FILE_STREAM_CLOSE 3 2026-09-24 "The MoPaQ archive library"
.SH NAME
libmpq__file_stream_close \- close and consume a logical MPQ member stream.
.SH SYNOPSIS
.nf
.B #include <libmpq/mpq.h>
.BI "int32_t libmpq__file_stream_close(mpq_file_stream_s *" stream ");"
.fi
.SH DESCRIPTION
Release retained offset-table state and the decoded block cache, then close the
private archive clone owned by \fIstream\fP. The handle is consumed regardless
of the returned status and must not be reused.
.SH RETURN VALUE
Returns \fBLIBMPQ_SUCCESS\fP or the first cleanup error while all cleanup is
still attempted.
.SH ERRORS
\fBLIBMPQ_ERROR_EXIST\fP reports a NULL stream. A clone close can report its
underlying close error.
.SH SEE ALSO
.BR libmpq__file_stream_open (3),
.BR libmpq__archive_close (3)
.SH AUTHOR
The libmpq project is maintained by Maik Broemme.
.SH REPORTING BUGS
Report bugs to <https://github.com/mbroemme/libmpq/issues>.
.SH COPYRIGHT
Copyright 2003-2026 Maik Broemme <mbroemme@libmpq.org>.
.PP
libmpq is free software, licensed under the GNU Lesser General Public
License, version 2.1 or later.
.PP
This manual is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
.PP
See the COPYING.LESSER file distributed with libmpq for the authoritative
license reference. The GNU license text is available at
<https://www.gnu.org/licenses/>.
