.\" Copyright (c) 2003-2026 Maik Broemme <mbroemme@libmpq.org>
.\"
.\" This manual is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License as
.\" published by the Free Software Foundation; either version 2.1 of
.\" the License, or (at your option) any later version.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this manual; if not, see <https://www.gnu.org/licenses/>.
.TH LIBMPQ__FILE_OFFSET 3 2026-08-12 "The MoPaQ archive library"
.SH NAME
libmpq__file_offset \- return a file's offset in an MPQ archive.
.SH SYNOPSIS
.nf
.B
#include <mpq.h>
.sp
.BI "int32_t libmpq__file_offset("
.BI "        mpq_archive_s  *" "mpq_archive",
.BI "        uint32_t        " "file_number",
.BI "        libmpq__off_t *" "offset"
.BI ");"
.fi
.SH DESCRIPTION
.PP
Call \fBlibmpq__file_offset\fP() to get a file's absolute byte offset in the archive.
.LP
The first argument is an archive handle opened by
\fBlibmpq__archive_open\fP(). The function stores the offset for
\fIfile_number\fP in \fIoffset\fP.
.SH RETURN VALUE
On success, a zero is returned and on error one of the following constants.
.TP
.B LIBMPQ_ERROR_EXIST
File does not exist in archive.
.SH SEE ALSO
.BR libmpq__archive_offset (3),
.SH AUTHOR
.TP
The libmpq project was started in 2003.
.B Maik Broemme <mbroemme@libmpq.org>
.PP
Use the email address above to report bugs, provide feedback, or suggest library enhancements.
