.\" Copyright (c) 2003-2026 Maik Broemme <mbroemme@libmpq.org>
.\"
.\" This manual is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License as
.\" published by the Free Software Foundation; either version 2.1 of
.\" the License, or (at your option) any later version.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this manual; if not, see <https://www.gnu.org/licenses/>.
.TH LIBMPQ__FILE_STREAM_OPEN_NAME 3 2026-09-24 "The MoPaQ archive library"
.SH NAME
libmpq__file_stream_open_name \- open a logical MPQ member stream by name.
.SH SYNOPSIS
.nf
.B #include <libmpq/mpq.h>
.BI "int32_t libmpq__file_stream_open_name(mpq_archive_s *" archive ", const char *" filename ", mpq_file_stream_s **" stream ");"
.fi
.SH DESCRIPTION
Resolve \fIfilename\fP and open its decoded logical file stream. The plaintext
filename is supplied during stream initialization when encrypted-member key
derivation requires it. The stream owns a private archive clone, starts at
zero, and outlives its source archive;
custom-I/O callback context remains caller-owned until close.
.SH RETURN VALUE
Returns \fBLIBMPQ_SUCCESS\fP and a stream, or an existing lookup, clone, or
allocation error with \fI*stream\fP NULL.
.SH ERRORS
\fBLIBMPQ_ERROR_EXIST\fP reports invalid input, a missing name, or writer mode.
.SH SEE ALSO
.BR libmpq__file_stream_open (3),
.BR libmpq__file_number (3)
.SH AUTHOR
The libmpq project is maintained by Maik Broemme.
.SH REPORTING BUGS
Report bugs to <https://github.com/mbroemme/libmpq/issues>.
.SH COPYRIGHT
Copyright 2003-2026 Maik Broemme <mbroemme@libmpq.org>.
.PP
libmpq is free software, licensed under the GNU Lesser General Public
License, version 2.1 or later.
.PP
This manual is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
.PP
See the COPYING.LESSER file distributed with libmpq for the authoritative
license reference. The GNU license text is available at
<https://www.gnu.org/licenses/>.
