.\" Copyright (c) 2003-2026 Maik Broemme <mbroemme@libmpq.org>
.\"
.\" This manual is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License as
.\" published by the Free Software Foundation; either version 2.1 of
.\" the License, or (at your option) any later version.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this manual; if not, see <https://www.gnu.org/licenses/>.
.TH LIBMPQ__VERSION 3 2026-08-12 "The MoPaQ archive library"
.SH NAME
libmpq__version \- return the libmpq package version.
.SH SYNOPSIS
.nf
.B
#include <libmpq/mpq.h>
.sp
.BI "const char *libmpq__version(void);"
.fi
.SH DESCRIPTION
.PP
Call \fBlibmpq__version\fP() to retrieve the package version for minimum-version checks.
.SH RETURN VALUE
The function returns the library version.
.SH SEE ALSO
.BR libmpq (3)
.SH AUTHOR
.TP
The libmpq project was started in 2003.
.B Maik Broemme <mbroemme@libmpq.org>
.PP
Use the email address above to report bugs, provide feedback, or suggest library enhancements.
