.TH LIBMPQ__FILE_ADD 3 2026-08-18 "The MoPaQ archive library"
.SH NAME
libmpq__file_add \- add an in-memory file to an MPQ archive
.SH SYNOPSIS
.B #include <libmpq/mpq.h>
.PP
.B int32_t libmpq__file_add(mpq_archive_s *archive, const char *name, const uint8_t *buffer, libmpq__off_t size, const mpq_file_create_options_s *options);
.SH DESCRIPTION
Adds a complete memory buffer using the same options as the streaming writer.
