# Include the manual pages in source distributions.
EXTRA_DIST			= $(man_MANS)

# Manual pages for the installed libmpq library API.
man_MANS =				\
	libmpq.3			\
	libmpq__archive_close.3		\
	libmpq__archive_clone.3		\
	libmpq__archive_files.3		\
	libmpq__archive_offset.3	\
	libmpq__archive_open.3		\
	libmpq__archive_size_packed.3	\
	libmpq__archive_size_unpacked.3	\
	libmpq__archive_version.3	\
	libmpq__archive_create.3	\
	libmpq__block_close_offset.3	\
	libmpq__block_open_offset.3	\
	libmpq__block_read.3		\
	libmpq__block_size_unpacked.3	\
	libmpq__file_blocks.3		\
	libmpq__file_compressed.3	\
	libmpq__file_encrypted.3	\
	libmpq__file_imploded.3		\
	libmpq__file_hash.3		\
	libmpq__file_number.3		\
	libmpq__file_number_from_hash.3	\
	libmpq__file_offset.3		\
	libmpq__file_read.3		\
	libmpq__file_begin.3		\
	libmpq__file_write.3		\
	libmpq__file_finish.3	\
	libmpq__file_add.3		\
	libmpq__file_add_path.3	\
	libmpq__file_size_packed.3	\
	libmpq__file_size_unpacked.3	\
	libmpq__strerror.3		\
	libmpq__version.3
