#!/usr/bin/env bash

# Copyright (c) 2026 Maik Broemme <mbroemme@libmpq.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.

set -euo pipefail

if (($# == 0)); then
	printf 'Usage: %s <source>...\n' "${0##*/}" >&2
	exit 2
fi

status=0
for source in "$@"; do
	if ! awk '
		FNR == 1 {
			previous = ""
		}
		FNR != 1 && /^[[:space:]]*\/(\*|\/)/ && previous !~ /^[[:space:]]*$/ {
			printf "%s:%d: standalone comment requires a preceding empty line\n", FILENAME, FNR
			failed = 1
		}
		{
			previous = $0
		}
		END {
			exit failed
		}
	' "${source}"; then
		status=1
	fi
done

exit "${status}"
