#!/usr/bin/env bash

# Copyright (c) 2026 Maik Broemme <mbroemme@libmpq.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.

set -euo pipefail

if (($# == 0)); then
	printf 'Usage: %s <source>...\n' "${0##*/}" >&2
	exit 2
fi

status=0
for source in "$@"; do
	if ! awk '
		FNR == 1 {
			previous = ""
			in_block = 0
			opener_line = 0
		}
		{
			line = $0
			if (in_block) {
				if (line ~ /^[[:space:]]*\*\/[[:space:]]*$/) {
					in_block = 0
				} else if (line ~ /\*\//) {
					printf "%s:%d: multiline block comment closer must be on its own line\n", FILENAME, FNR
					failed = 1
					in_block = 0
				} else if (line !~ /^[[:space:]]*\*/) {
					printf "%s:%d: multiline block comment line must start with '\''*'\''\n", FILENAME, FNR
					failed = 1
				}
				previous = line
				next
			}

			if (FNR != 1 && line ~ /^[[:space:]]*\/(\*|\/)/ && previous !~ /^[[:space:]]*$/) {
				printf "%s:%d: standalone comment requires a preceding empty line\n", FILENAME, FNR
				failed = 1
			}
			if (line ~ /^[[:space:]]*\/\*/) {
				remainder = line
				sub(/^[[:space:]]*\/\*/, "", remainder)
				if (remainder !~ /\*\//) {
					if (line !~ /^[[:space:]]*\/\*[[:space:]]*$/) {
						printf "%s:%d: multiline block comment opener must be on its own line\n", FILENAME, FNR
						failed = 1
					}
					in_block = 1
					opener_line = FNR
				}
			}
			previous = line
		}
		END {
			if (in_block) {
				printf "%s:%d: multiline block comment closer must be on its own line\n", FILENAME, opener_line
				failed = 1
			}
			exit failed
		}
	' "${source}"; then
		status=1
	fi
done

exit "${status}"
