/*
 *  crypt_buf_gen.c -- generate the static Storm/MPQ encryption table.
 *
 *  Copyright (c) 2003-2026 Maik Broemme <mbroemme@libmpq.org>
 *  Copyright (c) 2008-2026 Georg Lukas <georg@op-co.de>
 *
 *  This file is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This file is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this file; if not, see <https://www.gnu.org/licenses/>.
 *
 *
 *  Usage:
 *  $ make crypt_buf_gen
 *  $ ./crypt_buf_gen > crypt_buf.h
 *
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static uint32_t *buffer;

/* Allocate and fill the Storm/MPQ encryption table used by libmpq hashing and ciphers. */
int32_t
libmpq__buffer_init(void)
{
    buffer = malloc(sizeof(uint32_t) * 0x500);

    if (!buffer)
        return -1;

    uint32_t seed = 0x00100001;
    uint32_t index1 = 0;
    uint32_t index2 = 0;
    uint32_t i;

    /* The Storm table is generated as five interleaved 256-entry blocks. */
    for (index1 = 0; index1 < 0x100; index1++) {
        for (index2 = index1, i = 0; i < 5; i++, index2 += 0x100) {
            uint32_t temp1;
            uint32_t temp2;

            seed = (seed * 125 + 3) % 0x2AAAAB;
            temp1 = (seed & 0xFFFF) << 0x10;

            seed = (seed * 125 + 3) % 0x2AAAAB;
            temp2 = (seed & 0xFFFF);

            buffer[index2] = (temp1 | temp2);
        }
    }

    return 0;
}

/* Print the generated encryption table as a C header fragment. */
int
main(void)
{
    if (libmpq__buffer_init() != 0)
        perror("libmpq__buffer_init()");
    int x;
    printf("/* DO NOT EDIT: generated by tools/crypt_buf_gen.c. */\n");
    printf("static const uint32_t crypt_buf[0x500] = {\n\t");
    for (x = 0; x < 0x500; x++) {
        printf("0x%08x", buffer[x]);
        if (x < 0x500 - 1) {
            if (x % 6 == 5)
                printf(",\n\t");
            else
                printf(", ");
        }
    }
    printf("\n};\n");
}
